# Generated by Django 3.2.6 on 2021-08-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_tv', '0002_alter_show_release_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=14, unique=True)),
                ('allowed', models.BooleanField(default=True)),
                ('avatar', models.URLField(default='https://p4.wallpaperbetter.com/wallpaper/101/934/380/avatar-anime-avatar-the-last-airbender-aang-avatar-wallpaper-preview.jpg')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='show',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
